name: hunter_node_extract

on:
  workflow_dispatch:
  push:
    paths:
      - "hunter_node_extract.py"
      - "hunter_result.txt"
      - ".github/workflows/hunter_node_extract.yml"

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: install
      run: |
        pip install aiohttp pyyaml requests  

    - name: run
      env:
        HUNTER_TOKEN: ${{ secrets.HUNTER_TOKEN }}
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
      run: |
        python hunter_node_extract.py

    - name: commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        
        # 提交这三份文件到本地仓库
        git add hunter_nodes.yaml hunter_node_extract.csv hunter_result.txt
        
        # 只有在有实际变动时才 commit
        if ! git diff --cached --quiet; then
          git commit -m "update data: nodes, csv and result"
          git push
        else
          echo "没有文件变动，跳过 commit"
        fi