name: 1. 资产探测 (Masscan)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/scan_masscan.yml'

jobs:
  masscan_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装 Masscan
        run: sudo apt-get update && sudo apt-get install -y masscan

      - name: 扫描并固化 IP:Port 列表
        run: |
          # 核心网段：锁定高产区
          TARGET_RANGES="23.94.0.0/19,23.94.28.0/22,104.194.128.0/19,104.244.72.0/24,104.244.73.0/24,104.244.74.0/24,107.174.156.0/24,107.175.44.0/24,107.175.124.0/24,107.189.0.0/19,172.245.126.0/24"
          
          # 核心端口
          TARGET_PORTS="80,443,1333,1999,2052,2053,2082,2083,2087,2095,2096,2222,3002,3333,4444,5555,6001,6666,7777,8011,8080,8081,8083,8443,8444,8787,8888,8899,9050,9981,9999,10110,12202,18080,19999,54321,60001,60002"
          
          echo "[*] 开始 Masscan 定向探测..."
          
          sudo masscan $TARGET_RANGES -p"$TARGET_PORTS" --rate 5000 --wait 15 --open-only | \
          awk '/Discovered open port/ { split($4,p,"/"); print $6 ":" p[1] }' > temp_alive.txt
          
          sync
          
          LINES=$(wc -l < temp_alive.txt)
          echo "[*] 本次扫描共发现 $LINES 个存活端口。"
          
          # 更新逻辑
          if [ "$LINES" -gt 0 ]; then
            sort -u temp_alive.txt > alive_ips.txt
            echo "[+] 成功更新 alive_ips.txt"
          else
            echo "[!] 警告: 未扫描到新资产 (数量: $LINES)，保留旧数据。"
            # exit 1  # 可根据需要决定是否退出
          fi
          
          rm -f temp_alive.txt

      - name: 提交更改
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          if [[ -n $(git status -s alive_ips.txt) ]]; then
            git add alive_ips.txt
            git commit -m "Update: Refresh alive_ips.txt $(date +'%Y-%m-%d %H:%M') [skip ci]"
            git pull origin main --rebase
            git push origin main
          else
            echo "[-] alive_ips.txt 无变化，跳过本次提交。"
          fi