name: 自动化资产探测系统
on:
  workflow_dispatch: # 手动点击即可运行

jobs:
  stage1_masscan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: 安装 Masscan
        run: sudo apt-get update && sudo apt-get install -y masscan
      - name: 执行端口预扫
        run: |
          sudo masscan 38.207.0.0/16 -p80,443,7890,8080,8888,9090 --rate 2000 -oG scan_raw.txt
          grep "open" scan_raw.txt | awk '{print $4}' > alive_ips.txt
      - name: 保存存活列表
        uses: actions/upload-artifact@v4
        with:
          name: alive_ips
          path: alive_ips.txt

  stage2_verify:
    needs: stage1_masscan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 下载存活列表
        uses: actions/download-artifact@v4
        with:
          name: alive_ips
      - name: 安装 Python 依赖
        run: pip install aiohttp PyYAML
      - name: 深度解析指纹
        run: python scanner.py --file alive_ips.txt
      - name: 上传最终结果
        uses: actions/upload-artifact@v4
        with:
          name: found-configs
          path: results/
